### ISSUE TITLE
umongo-osx-all_1-6-1.zip corrupted ?

### ISSUE THREAD

**Issue by pierredewilde** [agirbal/umongo#210]
1. download 'umongo-osx-all_1-6-1.zip' from http://edgytech.com/umongo/
2. unzip it
3. run 'umongo.app'

=> error message: "umongo.app" is damaged and can’t be opened. You should move it to the Trash.

?

**Comment by agirbal** [comment]
It's typically because of osx's policy.

Readme says:
If your Mac tells you that the application is damaged, you can try a few things:
- go to "system preferences / security and privacy / General"
  Make sure that "allow applications downloaded from" is set to "anywhere".

I will make the README more explicit
