### ISSUE TITLE
Doc Builder Dialog Reset Button not working.

### ISSUE THREAD

**Issue by aadrian** [agirbal/umongo#79]
The Reset Button of the Doc Builder Dialog has no effect :(, it's not working.
Working on different type documents, makes this bug even more annoying, since this dialog always remember it's last content :(.

**Comment by agirbal** [comment]
Right now the reset buttons will reset all fields within the builder, but not clear all content. To clear all content, just delete the whole JSON blob from the parent box and then the builder should be empty when opening up. If not let me know how to reproduce.
I've removed the reset button in 1.4 since it doesnt help here.
